[package]
name = "zbc-fhe-tool"
version = "0.1.0"
authors = ["Zama <hello@zama.ai>"]
edition = "2021"
license = "Unlicense"
homepage = "https://github.com/zama-ai/zbc-fhe-tool"
repository = "https://github.com/zama-ai/zbc-fhe-tool"
publish = false

[dependencies]

rand = "^0.8"
clap = { version = "3.1.18", features = ["derive"] }
bincode = "1.3.3"
tfhe = { git = "https://github.com/zama-ai/tfhe-rs", rev = "ecf9d500589ba226a229885030a7c2b3c8e784e5" ,features = [ "boolean", "integer","shortint","x86_64-unix" ] }

# tfhe = { version = "0.2.1", features = ["boolean", "shortint", "integer", "x86_64-unix"] }

# Used for encoding and printing ciphertexts and keys
base64 = "0.13.0"
hex = "0.4.3"
sha256 = "1.1.1"

[dev-dependencies]
tempfile = "3.3.0"

[[bin]]
name = "zbc-fhe"
path = "src/bin/main.rs"

[profile.release]
lto = "fat"
