[package]
name = "zbc-fhe-tool"
version = "0.1.0"
authors = ["Zama <hello@zama.ai>"]
edition = "2021"
license = "Unlicense"
homepage = "https://github.com/zama-ai/zbc-fhe-tool"
repository = "https://github.com/zama-ai/zbc-fhe-tool"
publish = false

[dependencies]
bincode = "1.3.3"
clap = { version = "3.1.18", features = ["derive"] }
serde = "1.0"
tfhe = { git = "https://github.com/zama-ai/tfhe-rs.git", rev = "1d817c45d5234bcf33638406191b656998b30c2a", features = ["boolean", "experimental-force_fft_algo_dif4", "shortint", "integer"] }
