name: Publish fhevm-tfhe-cli

on: 
  workflow_dispatch:
    inputs:
      fhevm_tfhe_cli_tag:
        description: 'fhEVM-TFHE-CLI tool docker image tag (default: latest)'
        default: 'latest'
        type: string
        required: true
      ref_to_build_fhevm_tfhe_cli:
        description: 'Branch, tag or commit SHA1 to checkout fhEVM-TFHE-CLI (build)'
        required: true
        default: "main"
        type: string

env:
  DOCKER_IMAGE: ghcr.io/zama-ai/fhevm-tfhe-cli
  

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:

      - name: Check out fhevm-tfhe-cli
        uses: actions/checkout@v3
        with:
          repository: zama-ai/fhevm-tfhe-cli
          ref: ${{ inputs.ref_to_build_fhevm_tfhe_cli }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      
      - name: Check OS
        run: |
          lscpu
          uname -r
          lsb_release -a

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ inputs.fhevm_tfhe_cli_tag }},${{ env.DOCKER_IMAGE }}:latest
          labels: fhevm-tfhe-cli
